### ISSUE TITLE
More configurable logging levels

### ISSUE THREAD

**Issue by leifwalsh** [twosigma/nsncd#15]
At least: be able to turn on debug logging in an already built binary, probably with `env_logging`

Maybe: add a way to change the logging level for an already running daemon? Probably more than we need right now.

**Comment by toonn** [comment]
This would be very convenient. But in anticipation of this being implemented, how can the logging level be set at compile time? (I'm unfamiliar with Rust and I don't see any obvious variable that has the log level. I expected nsncd to have a flag to set the log level TBH but it doesn't even handle `--help`.) I'm trying to figure out why nsncd won't respond to requests for resolving subdomains of a `.local` domain.

**Comment by leifwalsh** [comment]
You get debug level logs in a debug build: https://slog-rs.github.io/slog/slog/index.html#notable-details

If you'd like to work on this, please go ahead, but I don't think anyone's needed more than that yet. Let us know if that doesn't work.

**Comment by leifwalsh** [comment]
please reopen with a reason if you do need this, but we haven't so far
