### ISSUE TITLE
provide host lookups

### ISSUE THREAD

**Issue by flokli** [twosigma/nsncd#37]
Requires implementing at least:

 - `RequestType::GETAI`
 - `RequestType::GETHOSTBYADDR`
 - `RequestType::GETHOSTBYADDRv6`
 - `RequestType::GETHOSTBYNAME`
 - `RequestType::GETHOSTBYNAMEv6`

**Comment by flokli** [comment]
@NinjaTrappeur and I have been taking a closer look at this and will send a PR once ready, just wanted to give a heads-up :-)

**Comment by flokli** [comment]
A branch containing all of #38, #39 and #40 can be found at my [host-lookups](https://github.com/flokli/nsncd/tree/host-lookups) branch. We sent individual PRs so things can be reviewed individually.

There's various people testing this on their systems, see https://github.com/NixOS/nixpkgs/issues/135888#issuecomment-1278129060 for details.

**Comment by flokli** [comment]
We combined #39 and #40 into #49, so they can be reviewed as a single unit.

**Comment by leifwalsh** [comment]
Done in #71
