### ISSUE TITLE
runtime configuration

### ISSUE THREAD

**Issue by leifwalsh** [twosigma/nsncd#42]
@flokli and @ninjatrappeur have been looking at adding support for more operations in #37.

The original purpose for, and our internal usage of, nsncd only needed user and group lookups to be served by nsncd, and while we're comfortable with the current performance and backpressure mechanisms, we have had some scares before where nsncd got overwhelmed by requests (hence #27 #28 #33 etc.). We're a little wary of adding more supported operations to our build.

I think we'd feel more comfortable if there were a way to configure which operations nsncd will handle, and all of us might appreciate runtime configuration anyway, to control the supported operations, threadpool settings, #15, etc.

I haven't looked at Rust configuration libraries but something that handles a common format like TOML and maybe supports environment variable overrides should be out there and sounds nice to me.

**Comment by leifwalsh** [comment]
https://docs.rs/config/latest/config/ and https://docs.rs/figment/latest/figment/ look promising at first glance.

**Comment by blinsay** [comment]
Clap also has support for env variables these days.

https://docs.rs/clap/latest/clap/builder/struct.Arg.html#method.env
