### ISSUE TITLE
Confusing log messages about nul termination

### ISSUE THREAD

**Issue by geofft** [twosigma/nsncd#7]
If you run e.g. `getent hosts 127.0.0.1`, that causes a GETHOSTBYNAME request looks something like

    02 00 00 00  06 00 00 00  04 00 00 00  7f 00 00 01

which causes nsncd to log "data provided contains an interior nul byte at byte pos 1" and drop the connection.

If you run e.g. `getent hosts 127.127.127.127`, that causes the request

    02 00 00 00  06 00 00 00  04 00 00 00  7f 7f 7f 7f

which logs "data provided is not nul terminated".

I think this is coming from the `CStr::from_bytes_with_nul` call in `Request::parse`, and I think we should not try to parse the argument as a NUL-terminated bytestring until we know that it's actually an operation that uses a NUL-terminated bytestring.

(This isn't a behavior bug, because we only support operations that use NUL-terminated bytestrings anyway, but it'd be nice to make the log spam go away - in particular every incoming ssh connection causes a reverse DNS lookup :) )

**Comment by leifwalsh** [comment]
Yep, https://github.com/twosigma/nsncd/blob/c2a4be3625dd4337ee1376553a679bd4e74fc74e/src/protocol.rs#L99 should just get whatever bytes are in the buffer, nuls or no, and https://github.com/twosigma/nsncd/blob/c2a4be3625dd4337ee1376553a679bd4e74fc74e/src/handlers.rs#L38 can decide whether it wants that to look like a nul terminated string or not.
